# Generated by Django 3.1 on 2020-12-13 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documentos', '0003_auto_20201213_1654'),
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaUser',
            fields=[
                ('idhistorial', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=10000)),
                ('idusuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.usuario')),
                ('signatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documentos.documento')),
            ],
        ),
    ]
