# Generated by Django 3.1 on 2020-12-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('iddocumento', models.AutoField(primary_key=True, serialize=False)),
                ('signatura', models.CharField(max_length=50)),
                ('siglo', models.CharField(max_length=7)),
                ('imagen', models.ImageField(upload_to='Documentos')),
            ],
        ),
    ]
