# Generated by Django 3.1 on 2020-12-13 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0002_auto_20201212_1328'),
        ('Usuarios', '0001_initial'),
        ('Documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='idarchivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Archivos.archivo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='idusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuarios.usuario'),
        ),
    ]
