# Generated by Django 3.1 on 2020-12-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0002_auto_20201213_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='iddocumento',
        ),
        migrations.AlterField(
            model_name='documento',
            name='signatura',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
