# Generated by Django 3.1 on 2020-12-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documentos', '0004_auto_20201213_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='contenido',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
