# Generated by Django 3.1 on 2020-12-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='imagen',
            field=models.ImageField(upload_to='Archivos'),
        ),
    ]
