# Generated by Django 3.1 on 2020-12-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('idArchivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=70)),
                ('imagen', models.ImageField(upload_to='Archivos')),
            ],
        ),
    ]
