# Generated by Django 3.1 on 2020-12-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pares3', '0003_auto_20201209_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
